"""empty message

Revision ID: 6e5dd40c8ccc
Revises: f4a1b30b08b8
Create Date: 2024-10-02 15:44:59.544521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e5dd40c8ccc'
down_revision = 'f4a1b30b08b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('num_chap', sa.Integer(), nullable=False),
    sa.Column('main_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'analysis_type', 'subject_id', 'num_chap')
    )
    op.create_table('knowledge',
    sa.Column('id_subject', sa.Integer(), nullable=False),
    sa.Column('num_chap', sa.Integer(), nullable=False),
    sa.Column('url_chap', sa.String(), nullable=False),
    sa.Column('latex_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_subject'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id_subject', 'num_chap')
    )
    op.create_table('temp_test',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=10), nullable=False),
    sa.Column('questions', sa.PickleType(), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('rate', sa.PickleType(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_date',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'test_type', 'subject')
    )
    op.create_table('todo_list',
    sa.Column('todo_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('todo_id', 'user_id')
    )
    op.drop_table('todo-list')
    op.drop_table('review-lessons')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review-lessons',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('subject_id', sa.VARCHAR(), nullable=False),
    sa.Column('chapter_id', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo-list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('todo_list')
    op.drop_table('test_date')
    op.drop_table('temp_test')
    op.drop_table('knowledge')
    op.drop_table('analysis')
    # ### end Alembic commands ###
