"""empty message

Revision ID: 8a64950daa32
Revises: 
Create Date: 2024-09-12 14:13:16.128399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a64950daa32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user-progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threadhold_1', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('threadhold_2', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('threadhold_3', sa.String(), nullable=True))
        batch_op.drop_column('threshold_1')
        batch_op.drop_column('threshold_2')
        batch_op.drop_column('threshold_3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user-progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threshold_3', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('threshold_2', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('threshold_1', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('threadhold_3')
        batch_op.drop_column('threadhold_2')
        batch_op.drop_column('threadhold_1')

    # ### end Alembic commands ###
