"""empty message

Revision ID: c9ac6c4ed890
Revises: f4e16e3c8908
Create Date: 2024-09-13 10:38:39.908226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9ac6c4ed890'
down_revision = 'f4e16e3c8908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review-lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review-lessons', schema=None) as batch_op:
        batch_op.drop_column('lesson_id')

    # ### end Alembic commands ###
