"""empty message

Revision ID: f4a1b30b08b8
Revises: 11ec0fd28004
Create Date: 2024-09-29 12:05:35.043049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a1b30b08b8'
down_revision = '11ec0fd28004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temp_test',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=10), nullable=False),
    sa.Column('questions', sa.PickleType(), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('rate', sa.PickleType(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temp_test')
    # ### end Alembic commands ###
