"""empty message

Revision ID: f4e16e3c8908
Revises: 8a64950daa32
Create Date: 2024-09-13 10:32:39.714199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e16e3c8908'
down_revision = '8a64950daa32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
