"""empty message

Revision ID: 0f034aa9f923
Revises: 2e575c4af782
Create Date: 2024-10-01 12:48:29.620389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f034aa9f923'
down_revision = '2e575c4af782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
