"""empty message

Revision ID: 39a2d8c2905c
Revises: a062e987a09d
Create Date: 2024-10-01 12:54:17.846099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a2d8c2905c'
down_revision = 'a062e987a09d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
