"""empty message

Revision ID: a062e987a09d
Revises: a0a2f2aa15fa
Create Date: 2024-10-01 12:50:11.165623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a062e987a09d'
down_revision = 'a0a2f2aa15fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
