"""Recreate Analysis table

Revision ID: a0a2f2aa15fa
Revises: 0f034aa9f923
Create Date: 2024-10-01 12:49:01.639994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a2f2aa15fa'
down_revision = '0f034aa9f923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge')
    op.drop_table('todo_list')
    op.drop_table('user-progress')
    op.drop_table('account')
    op.drop_table('temp_test')
    op.drop_table('test-record')
    op.drop_table('subject-category')
    op.drop_table('question-answer')
    op.drop_table('university')
    op.drop_table('subject')
    op.drop_table('analysis')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('analysis_type', sa.VARCHAR(), nullable=False),
    sa.Column('subject_id', sa.INTEGER(), nullable=False),
    sa.Column('num_chap', sa.INTEGER(), nullable=False),
    sa.Column('main_text', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('subject',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('rate', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('university',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('uni_code', sa.VARCHAR(), nullable=False),
    sa.Column('subject_category', sa.VARCHAR(), nullable=False),
    sa.Column('major_name', sa.VARCHAR(), nullable=False),
    sa.Column('major_code', sa.VARCHAR(), nullable=False),
    sa.Column('budget', sa.VARCHAR(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=2), nullable=False),
    sa.Column('pass_score', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question-answer',
    sa.Column('id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('difficulty', sa.INTEGER(), nullable=True),
    sa.Column('image', sa.VARCHAR(), nullable=True),
    sa.Column('question', sa.VARCHAR(), nullable=True),
    sa.Column('options', sa.VARCHAR(), nullable=True),
    sa.Column('answer', sa.INTEGER(), nullable=True),
    sa.Column('explain', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject-category',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('subject1', sa.VARCHAR(), nullable=False),
    sa.Column('subject2', sa.VARCHAR(), nullable=False),
    sa.Column('subject3', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test-record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('test_type', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.DATE(), nullable=False),
    sa.Column('knowledge', sa.VARCHAR(length=100), nullable=False),
    sa.Column('questions', sa.VARCHAR(), nullable=True),
    sa.Column('wrong_answer', sa.VARCHAR(), nullable=True),
    sa.Column('result', sa.VARCHAR(length=300), nullable=True),
    sa.Column('time_result', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp_test',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=10), nullable=False),
    sa.Column('questions', sa.BLOB(), nullable=False),
    sa.Column('chapter', sa.INTEGER(), nullable=False),
    sa.Column('time_limit', sa.INTEGER(), nullable=False),
    sa.Column('rate', sa.BLOB(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('pwd', sa.VARCHAR(length=300), nullable=False),
    sa.Column('uni_select', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('pwd'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user-progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('user_subject_cat', sa.VARCHAR(), nullable=True),
    sa.Column('user_major_uni', sa.INTEGER(), nullable=False),
    sa.Column('target_progress', sa.VARCHAR(), nullable=True),
    sa.Column('base_progress', sa.VARCHAR(), nullable=True),
    sa.Column('progress_1', sa.VARCHAR(), nullable=True),
    sa.Column('progress_2', sa.VARCHAR(), nullable=True),
    sa.Column('progress_3', sa.VARCHAR(), nullable=True),
    sa.Column('wrong_answer', sa.VARCHAR(), nullable=True),
    sa.Column('threadhold_1', sa.VARCHAR(), nullable=True),
    sa.Column('threadhold_2', sa.VARCHAR(), nullable=True),
    sa.Column('threadhold_3', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_major_uni'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('todo_list',
    sa.Column('todo_id', sa.VARCHAR(length=1), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.VARCHAR(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('todo_id', 'user_id')
    )
    op.create_table('knowledge',
    sa.Column('id_subject', sa.INTEGER(), nullable=False),
    sa.Column('num_chap', sa.INTEGER(), nullable=False),
    sa.Column('url_chap', sa.VARCHAR(), nullable=False),
    sa.Column('latex_text', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['id_subject'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id_subject', 'num_chap')
    )
    # ### end Alembic commands ###
